=begin
#Scalyr API

#You can use the Scalyr API to send and retrieve log data directly from Scalyr servers, as well as manage configuration files. It is usually most convenient to use the Scalyr Agent to send log files, and to view logs on the web site.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Scalyr::ScalyrApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScalyrApi' do
  before do
    # run before each test
    @api_instance = Scalyr::ScalyrApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScalyrApi' do
    it 'should create an instance of ScalyrApi' do
      expect(@api_instance).to be_instance_of(Scalyr::ScalyrApi)
    end
  end

  # unit tests for add_user_to_group
  # This method adds one or more users to a group.
  # This method adds one or more users to a group.
  # @param users_to_group_request Users that need to be added to the group
  # @param [Hash] opts the optional parameters
  # @return [UpdateUsers]
  describe 'add_user_to_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
