=begin
#Scalyr API

#You can use the Scalyr API to send and retrieve log data directly from Scalyr servers, as well as manage configuration files. It is usually most convenient to use the Scalyr Agent to send log files, and to view logs on the web site.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

# Common files
require 'scalyr/api_client'
require 'scalyr/api_error'
require 'scalyr/version'
require 'scalyr/configuration'

# Models
require 'scalyr/models/update_users'
require 'scalyr/models/users_to_group'

# APIs
require 'scalyr/api/scalyr_api'

module Scalyr
  class << self
    # Customize default settings for the SDK using block.
    #   Scalyr.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
